# -*- coding: utf-8 -*-
"""HugingFace_TextGenerator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hjih0Fb-kOX5Wd61Yotay06Yx-hKGPxz
"""

# !pip install transformers
# !pip install sentencepiece

import transformers

from transformers import pipeline

generator = pipeline('text-generation', model= 'distilgpt2')

generator(
    'Today I am going to showcase our platform where',
    max_length= 100,
    num_return_sequences=4,
)

